name: sanity

on:
  push:
      branches: [main]
  pull_request:
      branches: [main]

jobs:
  backport:
      runs-on: ubuntu-latest
      steps:
          - name: Setup repo
            uses: actions/checkout@v3

          - uses: denoland/setup-deno@main
            with:
                deno-version: v1.x

          - name: Run backporting
            run: deno task backport

  format-and-lint:
      runs-on: ubuntu-latest
      steps:
          - name: Setup repo
            uses: actions/checkout@v3

          - uses: denoland/setup-deno@main
            with:
                deno-version: v1.x

          - name: Check Format
            run: deno fmt --check

          - name: Lint
            run: deno lint

  test:
      runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

      strategy:
          matrix:
              os: [macOS-latest, windows-latest, ubuntu-latest]

      steps:
          - name: Setup repo
            uses: actions/checkout@v3

          - uses: denoland/setup-deno@main
            with:
                deno-version: v1.x

          - name: Run type checking
            run: deno task check

          - name: Run Tests
            run: deno task test

  coverage:
      runs-on: ubuntu-latest
      steps:
          - name: Setup repo
            uses: actions/checkout@v3
            with:
                fetch-depth: 0

          - uses: denoland/setup-deno@main
            with:
                deno-version: v1.x

          - name: Create coverage files
            run: deno task coverage

          - name: Collect coverage
            uses: codecov/codecov-action@v1.0.10 # upload the report on Codecov
            with:
                file: ./coverage.lcov