name: release

on:
  push:
      tags:
          - "v1.*"

jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: denoland/setup-deno@main
              with:
                  deno-version: v1.x

            - name: Backport
              run: deno task backport
                
            - name: Publish to npm
              run: |
                  npm config set //registry.npmjs.org/:_authToken '${NPM_TOKEN}'
                  npm publish --ignore-scripts
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
